version: '2.4'
networks:
  kek:
    driver: bridge

services:
  code:
    image: "final_project"
    container_name: main_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - kek
    depends_on:
      - redis
      - db

  storage:
    image: 'final_project'
    command: 'start_storage_service'
    container_name: storage
    networks:
      - kek
    ports:
      - 8001:8001

  worker:
    image: 'final_project'
    command: 'rq worker --url redis://redis:6379'
    networks:
      - kek
    depends_on:
      - redis
      - db


  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=evgeny
      - POSTGRES_PASSWORD=5211
      - POSTGRES_DB=database
    networks:
      - kek
    ports:
      - 5432:5432



  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./redis.conf:/opt/bitnami/redis/etc/redis.conf
    ports:
      - 6379:6379
    networks:
      - kek