version: '2.4'

services:
  code:
    image: "final_project"
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  storage:
    image: 'final_project'
    command: 'start_storage_service'
    ports:
      - 8001:8001

  worker:
    image: 'final_project'
    command: 'rq worker --url redis://redis:6379'
    depends_on:
      - redis
      - db


  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=evgeny
      - POSTGRES_PASSWORD=5211
      - POSTGRES_DB=database
    ports:
      - 5432:5432



  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./redis.conf:/opt/bitnami/redis/etc/redis.conf
    ports:
      - 6379:6379